# Generated by Django 5.2.5 on 2025-08-28 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'hardware'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='issues.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('employee', 'employee'), ('hardware', 'hardware'), ('manager', 'manager'), ('admin', 'admin')], default='employee', max_length=20),
        ),
    ]
