# Generated by Django 5.2.5 on 2025-08-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_issue_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='floor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
