# Generated by Django 5.2.5 on 2025-08-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_issue_floor_issue_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='subcategory',
            field=models.CharField(blank=True, choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(blank=True, choices=[('hardware', 'Hardware'), ('application', 'Application'), ('network', 'Network'), ('Middle Ware', 'Middle Ware'), ('others', 'Others')], max_length=100),
        ),
    ]
