# Generated by Django 5.2.5 on 2025-08-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_issue_subcategory_alter_issue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('Kiosk', 'Kiosk'), ('P2P', 'P2P'), ('BSNL', 'BSNL'), ('Others', 'Others'), ('VMS', 'VMS'), ('Airtel', 'Airtel'), ('Weighing Scale', 'Weighing Scale'), ('SAP', 'SAP'), ('Vodaphone', 'Vodaphone'), ('PineLabs', 'PineLabs'), ('POS', 'POS'), ('Zakya', 'Zakya'), ('Printer', 'Printer'), ('Computer', 'Computer'), ('Server', 'Server'), ('PayTM', 'PayTM'), ('PetPooja', 'PetPooja')], max_length=100),
        ),
    ]
