# Generated by Django 5.2.5 on 2025-08-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_alter_issue_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='subcategory',
            field=models.CharField(blank=True, choices=[], max_length=100),
        ),
    ]
