# Generated by Django 5.2.5 on 2025-08-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_alter_issue_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('POS', 'POS'), ('Printer', 'Printer'), ('Computer', 'Computer'), ('Server', 'Server'), ('Weighing Scale', 'Weighing Scale'), ('Kiosk', 'Kiosk'), ('Airtel', 'Airtel'), ('BSNL', 'BSNL'), ('Vodaphone', 'Vodaphone'), ('SAP', 'SAP'), ('Zakya', 'Zakya'), ('P2P', 'P2P'), ('VMS', 'VMS'), ('PetPooja', 'PetPooja'), ('PineLabs', 'PineLabs'), ('PayTM', 'PayTM'), ('Others', 'Others')], max_length=100),
        ),
    ]
